title: Shrey's Blog
author: Shrey Aggarwal
email: mail.shrey.aggarwal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a senior in high school who plays soccer, going to rutgers for college, and loves to play video games with his friends. 

# social links
instagram_username: shrey_325 # DO NOT include the @ character, or else the build will fail!
github_username:  shrey325 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
